# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://selfie.davidlj95.com
title: davidlj95's Selfie
author: davidlj95
description: > # "Description of this stuff
  Just an special (and my favourite) own selfie
